# Generated by Django 5.2.8 on 2025-12-11 18:49

import bmstu_lab.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('eta', models.CharField(blank=True, max_length=20, verbose_name='ожидание')),
                ('img_url', models.TextField(blank=True, null=True, verbose_name='адрес картинки')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='пометка удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='когда пометили')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'db_table': 'support_services',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email адрес')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='имя пользователя')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='Является ли пользователь менеджером?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Является ли пользователь админом?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
            managers=[
                ('objects', bmstu_lab.models.NewUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('deleted', 'удалён'), ('formed', 'сформирован'), ('finished', 'завершён'), ('rejected', 'отклонён')], default='draft', max_length=50, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('requested_at', models.DateTimeField(blank=True, null=True, verbose_name='дата формирования')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='дата завершения')),
                ('room', models.CharField(blank=True, max_length=50, null=True, verbose_name='кабинет')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='пометка удалено')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='когда пометили')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='инженер')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'db_table': 'support_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportRequestService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1, verbose_name='количество')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('ok', models.BooleanField(blank=True, null=True, verbose_name='галочка')),
                ('support_requests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.supportrequest', verbose_name='заявка')),
                ('support_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bmstu_lab.supportservice', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'строка заявки',
                'verbose_name_plural': 'строки заявки',
                'db_table': 'support_request_service',
                'ordering': ['support_requests_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('support_requests', 'support_service'), name='uniq_support_request_service')],
            },
        ),
    ]
