# Generated by Django 5.2.8 on 2025-11-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequestservice',
            name='ok',
            field=models.BooleanField(blank=True, null=True, verbose_name='галочка'),
        ),
    ]
