# Generated by Django 5.2.8 on 2026-05-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KBArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержание')),
                ('description', models.TextField(help_text='English description for SigLIP embedding. Required.', verbose_name='описание (англ., для SigLIP)')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='теги')),
                ('category', models.CharField(choices=[('network', 'Сеть и VPN'), ('printer', 'Принтеры и сканеры'), ('software', 'Установка ПО'), ('hardware', 'Оборудование'), ('email', 'Почта и календарь'), ('access', 'Доступы и учётные записи'), ('other', 'Прочее')], default='other', max_length=50, verbose_name='категория')),
                ('img_url', models.TextField(blank=True, null=True, verbose_name='URL скриншота')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'статья БЗ',
                'verbose_name_plural': 'статьи БЗ',
                'db_table': 'kb_articles',
                'ordering': ['id'],
            },
        ),
    ]
