# Generated by Django 5.2.8 on 2026-05-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_kbarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbarticle',
            name='confluence_page_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID страницы Confluence'),
        ),
    ]
