# Generated by Django 5.2.8 on 2026-05-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0003_kbarticle_confluence_page_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='KBArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField(verbose_name='URL изображения')),
                ('alt_text', models.CharField(blank=True, max_length=500, verbose_name='alt / описание')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='порядок')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bmstu_lab.kbarticle', verbose_name='статья')),
            ],
            options={
                'verbose_name': 'изображение статьи БЗ',
                'verbose_name_plural': 'изображения статей БЗ',
                'db_table': 'kb_article_images',
                'ordering': ['article_id', 'sort_order'],
            },
        ),
    ]
